# YAML format - property-name followed by colon, followed by a MANDATORY space, followed by property-value
daak:
  naam: Gadha

com:
  ad:
    nickname: ${daak.naam}
    spouse-name: Maisha
    firstname: Adeeb
    last-name: Siddiqui
    age: 33.5
    family:
      - father: Abbu
        mother: Ammu
        brother: Fayaz
      - father: Shoshur
        mother: Shashuri
        brother: Barru
    phones:
      first: nokia
      second: nexus
      third: motorola

# .yml can also hold properties without indentation like com.ad.firstname: Adeeb