# YAML format - property-name followed by colon, followed by a MANDATORY space, followed by property-value
# .yml can also hold properties without indentation e.g. com.ad.firstname: Adeeb
daak:
  naam: dev

com:
  ad:
    nickname: ${daak.naam}
    spouse-name: Maisha
    firstname: Adeeb
    last-name: Siddiqui
    age: 33.5
    family:
      - father: Abbu
        mother: Ammu
        brother: Fayaz
      - father: Shoshur
        mother: Shashuri
        brother: Barru
    phones:
      first: nokia
      second: nexus
      third: motorola

# application.yml holds the configuration for default profile, the properties of which are always loaded unless overridden