daak:
  naam: Gadha

com:
  ad:
    nickname: ${daak.naam}
    spouse-name: Maisha
    firstname: Adeeb
    last-name: Siddiqui
    age: 33.5
    family:
      - father: Abbu
        mother: Ammu
        brother: Fayaz
      - father: Shoshur
        mother: Shashuri
        brother: Barru

# .yml can hold .properties style properties as well. example: com.ad.firstname=Adeeb